# Site settings
title: Karen Loscocco
email: Karen.Loscocco@gatech.edu
url: https://karenaloscocco.github.io/portfolio/
description: "Seeking 2021 full-time position in data science within a company that embraces creativity and innovation."
keywords: #"your keywords, separated by commas"
skills: "Georgia Tech - Industrial Engineering - Analytics and Data Science - Dec 2020 Graduation"
meta_author: Loscocco Karen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 86dbd4 #1399AE #00A7C1 #cfd1ff #18bc9c #80B3FF
  primary-rgb: abf4ff #bae2e8 #"186, 226, 232" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A edeeff
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  name: Karen Loscocco
  location: Location
  social: Around the Web
  credits: About Freelancer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/karen-loscocco
  - title: github
    url: https://github.com/KarenALoscocco

# Postal address (add as many lines as necessary)
address:
  - line: Atlanta, GA

# Credits content
credits: 'Freelancer is a free to use, MIT licensed Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
